services:
  web1:
    image: nginx:latest
    ports:
      - 8080:80 
    volumes:
      - ./html/index.html:/usr/share/nginx/html/index.html
      

  web2:
    image: nginx:latest
    ports:
      - 6060:80
    volumes:
      - ./html/main.html:/usr/share/nginx/html/index.html


  redis:
    image: redis.latest
